repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.2
    hooks:
      - id: pylint
        args: ['--ignore=migrations,env.py', '--logging-format-style=fstr']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
      - id: mypy
  - repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1
    hooks:
      - id: pydocstyle
        args: ['--ignore=D1,D203,D212']
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
